set(ESMFMKFILE "$ENV{ESMFMKFILE}" CACHE FILEPATH "Installed ESMF esmf.mk")
if(NOT EXISTS "${ESMFMKFILE}")
  message(FATAL_ERROR "Paper ESMF requested: set ESMFMKFILE to the installed esmf.mk")
endif()
find_program(PAPER_MAKE NAMES gmake make REQUIRED)
execute_process(COMMAND "${PAPER_MAKE}" --no-print-directory -s -f "${CMAKE_CURRENT_LIST_DIR}/query_esmf.mk" "ESMFMKFILE=${ESMFMKFILE}" query RESULT_VARIABLE _rc OUTPUT_VARIABLE _metadata ERROR_VARIABLE _error)
if(NOT _rc EQUAL 0)
  message(FATAL_ERROR "Unable to query ESMF metadata: ${_error}")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/esmf-metadata.txt" "${_metadata}")
foreach(_kind COMPILE LINK VERSION)
  string(REGEX MATCH "${_kind}=([^\n]*)" _match "${_metadata}")
  set(PAPER_ESMF_${_kind} "${CMAKE_MATCH_1}")
endforeach()
separate_arguments(_compile UNIX_COMMAND "${PAPER_ESMF_COMPILE}")
list(FILTER _compile EXCLUDE REGEX "^-std=|^-DESMF_CXXSTD=")
separate_arguments(_link UNIX_COMMAND "${PAPER_ESMF_LINK}")
add_library(PaperESMF INTERFACE IMPORTED)
set_property(TARGET PaperESMF PROPERTY INTERFACE_COMPILE_OPTIONS "${_compile}")
set_property(TARGET PaperESMF PROPERTY INTERFACE_LINK_LIBRARIES "${_link}")
set(PaperESMF_FOUND TRUE)
