include $(ESMFMKFILE)
.PHONY: query
query:
	@echo COMPILE=$(ESMF_CXXCOMPILEPATHS) $(ESMF_CXXCOMPILECPPFLAGS) $(ESMF_CXXCOMPILEOPTS)
	@echo LINK=$(ESMF_CXXLINKPATHS) $(ESMF_CXXLINKRPATHS) $(ESMF_CXXLINKOPTS) $(ESMF_CXXESMFLINKLIBS)
	@echo VERSION=$(ESMF_VERSION_STRING)
